import OpenAI from 'openai';
import { env } from '../config/env.js';

export const openai = env.OPENAI_API_KEY
  ? new OpenAI({ apiKey: env.OPENAI_API_KEY })
  : null;

export async function generateContent(prompt, contentType = 'post') {
  if (!openai) {
    return generatePlaceholderContent(prompt, contentType);
  }

  try {
    const systemPrompt = getSystemPrompt(contentType);

    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
      max_tokens: 500
    });

    const content = response.choices[0].message.content;
    const hashtags = extractHashtags(content);

    return {
      text: content,
      hashtags,
      suggestions: generateSuggestions(content),
      aiEnhanced: true
    };
  } catch (error) {
    console.error('OpenAI error:', error);
    return generatePlaceholderContent(prompt, contentType);
  }
}

export async function enrichContent(content) {
  if (!openai) {
    return generatePlaceholderEnrichment(content);
  }

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'system',
          content: 'You are an expert social media content optimizer. Improve the given content for maximum engagement while maintaining the original message. Return only the improved content.'
        },
        { role: 'user', content: `Enhance this content: ${content}` }
      ],
      temperature: 0.7,
      max_tokens: 300
    });

    const enriched = response.choices[0].message.content;
    const score = calculateEngagementScore(enriched);

    return {
      enriched,
      score,
      suggestions: [
        'Add relevant hashtags',
        'Include a call-to-action',
        'Optimize for engagement'
      ]
    };
  } catch (error) {
    console.error('OpenAI enrichment error:', error);
    return generatePlaceholderEnrichment(content);
  }
}

function getSystemPrompt(contentType) {
  const prompts = {
    post: 'Create an engaging social media post that is concise, relatable, and encourages interaction.',
    article: 'Create an informative article outline with key points and call-to-action.',
    email: 'Create a compelling email that converts readers to action.'
  };
  return prompts[contentType] || prompts.post;
}

function extractHashtags(text) {
  const hashtagRegex = /#\w+/g;
  return text.match(hashtagRegex) || [];
}

function generateSuggestions(content) {
  return [
    'Engaging post about the topic',
    'Professional version for LinkedIn',
    'Casual version for Twitter/X'
  ];
}

function calculateEngagementScore(content) {
  let score = 50;
  if (content.length > 100) score += 10;
  if (content.includes('?')) score += 5;
  if (content.includes('!')) score += 5;
  if (/(http|https):\/\//.test(content)) score += 10;
  return Math.min(score, 100);
}

function generatePlaceholderContent(prompt, contentType) {
  return {
    text: `${prompt}\n\n✨ Generated by PostAI\n\n#AI #SocialMedia #Automation`,
    hashtags: ['#AI', '#SocialMedia', '#Automation', '#PostAI'],
    suggestions: [
      `Engaging ${contentType} about: ${prompt}`,
      'Professional version for LinkedIn',
      'Casual version for social media'
    ],
    aiEnhanced: false
  };
}

function generatePlaceholderEnrichment(content) {
  return {
    enriched: `${content} ✨ Enhanced with AI`,
    score: 75,
    suggestions: [
      'Add relevant hashtags',
      'Include a call-to-action',
      'Optimize for engagement'
    ]
  };
}
