import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

// Root endpoint
app.get('/', (req, res) => {
  res.json({ 
    message: "PostAI Backend API",
    status: "running",
    endpoints: {
      health: "/health",
      api: "/api"
    },
    timestamp: new Date().toISOString()
  });
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Main API endpoint
app.get('/api', (req, res) => {
  res.json({ 
    message: "Backend working!", 
    key: process.env.API_KEY ? "API key is set" : "no key set",
    timestamp: new Date().toISOString()
  });
});

// Generate content endpoint (for form submissions)
app.post('/api', (req, res) => {
  const { prompt } = req.body;
  
  if (!prompt) {
    return res.status(400).json({ 
      error: "Prompt is required",
      message: "Please provide a prompt in the request body"
    });
  }

  // For now, return a simple response
  // Later you can integrate OpenAI, Notion, or other services here
  res.json({
    success: true,
    message: "Content generation endpoint is ready!",
    prompt: prompt,
    note: "Connect your AI service (OpenAI, etc.) to generate actual content",
    timestamp: new Date().toISOString()
  });
});

// Advanced content generation endpoint
app.post('/api/generate', async (req, res) => {
  try {
    const { contentType, prompt, platforms, schedule, scheduledTime } = req.body;
    
    if (!prompt) {
      return res.status(400).json({ 
        error: "Prompt is required",
        message: "Please provide a prompt"
      });
    }

    if (!platforms || platforms.length === 0) {
      return res.status(400).json({ 
        error: "Platforms required",
        message: "Please select at least one platform"
      });
    }

    // Simulate AI content generation
    // In production, integrate with OpenAI, Claude, or other AI services
    const generatedContent = {
      contentType: contentType || 'post',
      originalPrompt: prompt,
      platforms: platforms,
      content: {
        text: `🚀 ${prompt}\n\n✨ Generated by PostAI - Your AI-powered social media assistant!\n\n#AI #SocialMedia #Automation`,
        hashtags: ['#AI', '#SocialMedia', '#Automation', '#PostAI'],
        suggestions: [
          `Engaging post about: ${prompt}`,
          `Professional version for LinkedIn`,
          `Casual version for Twitter`
        ]
      },
      schedule: schedule || false,
      scheduledTime: scheduledTime || null,
      status: schedule ? 'scheduled' : 'ready',
      timestamp: new Date().toISOString()
    };

    // If API_KEY is set, you could call OpenAI here
    if (process.env.API_KEY && process.env.API_KEY.startsWith('sk-')) {
      // OpenAI integration would go here
      generatedContent.aiEnhanced = true;
      generatedContent.note = "AI enhancement available (OpenAI key detected)";
    }

    res.json({
      success: true,
      message: "Content generated successfully!",
      data: generatedContent,
      nextSteps: [
        "Review the generated content",
        "Customize if needed",
        "Publish to selected platforms",
        schedule ? `Scheduled for ${scheduledTime}` : "Publish now"
      ]
    });

  } catch (error) {
    res.status(500).json({
      error: "Content generation failed",
      message: error.message
    });
  }
});

// Schedule management endpoints
app.get('/api/schedules', (req, res) => {
  // In production, fetch from database
  res.json({
    schedules: [],
    message: "Schedule management endpoint ready"
  });
});

app.post('/api/schedules', (req, res) => {
  const { content, platforms, scheduledTime } = req.body;
  
  res.json({
    success: true,
    message: "Content scheduled successfully",
    scheduleId: `schedule_${Date.now()}`,
    scheduledTime: scheduledTime,
    platforms: platforms
  });
});

// Platform publishing endpoints
app.post('/api/publish', async (req, res) => {
  const { content, platforms } = req.body;
  
  // In production, integrate with platform APIs (Twitter, Facebook, etc.)
  const results = platforms.map(platform => ({
    platform: platform,
    status: 'success',
    postId: `${platform}_${Date.now()}`,
    message: `Posted to ${platform} successfully`
  }));

  res.json({
    success: true,
    message: "Content published successfully",
    results: results
  });
});

// Content enrichment endpoint
app.post('/api/enrich', (req, res) => {
  const { content } = req.body;
  
  res.json({
    success: true,
    original: content,
    enriched: {
      text: content + " ✨ Enhanced with AI",
      suggestions: [
        "Add relevant hashtags",
        "Include a call-to-action",
        "Optimize for engagement"
      ],
      score: 85
    }
  });
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Backend running on port ${PORT}`));

