export async function generateContent(req, res, next) {
  try {
    const { contentType, prompt, platforms, schedule, scheduledTime } = req.body || {};

    const trimmedPrompt = (prompt || '').trim();

    if (!trimmedPrompt) {
      return res.status(400).json({ success: false, message: 'Prompt is required' });
    }

    if (trimmedPrompt.length > 1000) {
      return res.status(400).json({ success: false, message: 'Prompt is too long' });
    }

    if (!platforms || !Array.isArray(platforms) || platforms.length === 0) {
      return res.status(400).json({ success: false, message: 'At least one platform is required' });
    }

    const text = `🚀 ${trimmedPrompt}\n\n✨ Generated by PostAI - Your AI-powered social media assistant!\n\n#AI #SocialMedia #Automation`;

    const content = text;

    const meta = {
      contentType: contentType || 'post',
      platforms,
      schedule: !!schedule,
      scheduledTime: schedule ? scheduledTime || null : null,
      model: 'stub',
      tokensUsed: null
    };

    return res.json({ success: true, content, meta });
  } catch (error) {
    return next(error);
  }
}

export async function enrichContent(req, res, next) {
  try {
    const { content } = req.body || {};

    const trimmed = (content || '').trim();

    if (!trimmed) {
      return res.status(400).json({ success: false, message: 'Content is required' });
    }

    if (trimmed.length > 2000) {
      return res.status(400).json({ success: false, message: 'Content is too long' });
    }

    const enriched = `${trimmed} ✨ Enhanced with AI`;

    const meta = {
      operation: 'enrich',
      model: 'stub',
      tokensUsed: null
    };

    return res.json({ success: true, content: enriched, meta });
  } catch (error) {
    return next(error);
  }
}
